service:
 name: touroll

plugins:
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs14.x
 iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource:
      - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
      - "arn:aws:s3:::touroll/*"


functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: dist/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}